"""通用 RAG Core 的公共入口。"""

from rag_app.core.capabilities import (
    ComponentCapabilities,
    ComponentDescriptor,
    ComponentKind,
    ProviderMode,
)
from rag_app.core.errors import (
    CapabilityMismatch,
    CapabilityUnavailable,
    ComponentNotRegistered,
    ConfigurationError,
    Conflict,
    IndexCompatibilityError,
    InvalidDocument,
    NotFound,
    PolicyDenied,
    ProviderAuthenticationError,
    ProviderInputTooLarge,
    ProviderInvalidResponse,
    ProviderRateLimited,
    ProviderUnavailable,
    RagError,
    RevisionStateError,
    UnsupportedDocumentFeature,
    ValidationFailed,
)
from rag_app.core.events import TraceEvent
from rag_app.core.fingerprints import (
    IndexFingerprintInput,
    ServingFingerprintInput,
    canonical_index_payload,
    canonical_serving_payload,
    compute_index_fingerprint,
    compute_serving_fingerprint,
)
from rag_app.core.identifiers import (
    canonical_json,
    canonical_sha256,
    chunk_id,
    deterministic_id,
    document_version_id,
    new_id,
    node_id,
    validate_id,
)
from rag_app.core.models import *  # noqa: F403
from rag_app.core.policies import CircuitBreakerPolicy, EgressPolicy

__all__ = [
    "CapabilityMismatch",
    "CapabilityUnavailable",
    "CircuitBreakerPolicy",
    "ComponentCapabilities",
    "ComponentDescriptor",
    "ComponentKind",
    "ComponentNotRegistered",
    "ConfigurationError",
    "Conflict",
    "EgressPolicy",
    "IndexCompatibilityError",
    "IndexFingerprintInput",
    "InvalidDocument",
    "NotFound",
    "PolicyDenied",
    "ProviderAuthenticationError",
    "ProviderInputTooLarge",
    "ProviderInvalidResponse",
    "ProviderMode",
    "ProviderRateLimited",
    "ProviderUnavailable",
    "RagError",
    "RevisionStateError",
    "ServingFingerprintInput",
    "TraceEvent",
    "UnsupportedDocumentFeature",
    "ValidationFailed",
    "canonical_index_payload",
    "canonical_json",
    "canonical_serving_payload",
    "canonical_sha256",
    "chunk_id",
    "compute_index_fingerprint",
    "compute_serving_fingerprint",
    "deterministic_id",
    "document_version_id",
    "new_id",
    "node_id",
    "validate_id",
]
